#!/bin/sh
#
# List of meta-layer to be fetched
#
# Copyright (C) 2015 Guy Morand
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# path;URL;branch, tag or revision
################################################################################
# Poky meta-layers
#poky;git://git.yoctoproject.org/poky.git;master
poky;http://git.yoctoproject.org/git/poky;master

# Openembedded meta-layer
#poky/meta-openembedded;git://git.openembedded.org/meta-openembedded;master
poky/meta-openembedded;https://github.com/openembedded/meta-openembedded.git;master

# Rapsberry PI meta-layer
#poky/meta-raspberrypi;git://git.yoctoproject.org/meta-raspberrypi;master
poky/meta-raspberrypi;http://git.yoctoproject.org/git/meta-raspberrypi;master

# Random Guy's Raspberry PI meta-layer
#poky/meta-random-guy-rpi;git@github.com:random85/meta-random-guy-rpi.git;master
poky/meta-random-guy-rpi;https://github.com/random85/meta-random-guy-rpi.git;master
